name: PR Welcome & Thanks

on:
  pull_request:
    types:
      - opened
      - closed   # to detect merged PRs

jobs:
  comment-on-pr-open:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Comment on new pull request
        uses: actions/github-script@v7
        with:
          script: |
            const login = context.payload.sender.login;
            const pr_number = context.payload.pull_request.number;

            const repoName = "Vipreshana";
            const repoUrl = "https://github.com/sailaja-adapa/Vipreshana";
            const ownerName = "sailaja-adapa";
            const ownerUrl = "https://github.com/sailaja-adapa";

            const message = `Thank you for your contribution! ğŸ™Œ\n\nWeâ€™ll review your PR shortly. Stay tuned! ğŸ˜Š\n\nMeanwhile, if you havenâ€™t already, consider starring â­ [Vipreshana](${repoUrl}) to support the project!\n\nAnd also add follow [${ownerName}](${ownerUrl}) project admin.`;

            await github.rest.issues.createComment({
              issue_number: pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

  comment-on-pr-merged:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Comment after PR merged
        uses: actions/github-script@v7
        with:
          script: |
            const login = context.payload.pull_request.user.login;
            const pr_number = context.payload.pull_request.number;

            const repoName = "Vipreshana";
            const repoUrl = "https://github.com/sailaja-adapa/Vipreshana";
            const ownerName = "sailaja-adapa";
            const ownerUrl = "https://github.com/sailaja-adapa";

            const message = `PR successfully merged! ğŸš€\n\nThanks a lot for your valuable contribution! ğŸ’–\n\nKeep up the great work, and donâ€™t forget to â­ [Vipreshana](${repoUrl}) if you havenâ€™t yet â€” your support means a lot! ğŸ™\n\nAnd also add follow [${ownerName}](${ownerUrl}) project admin.`;

            await github.rest.issues.createComment({
              issue_number: pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
